### ISSUE TITLE
updating error during the upgrade of Quickblox sdk from 3.3.5 to 3.4.1 

### ISSUE THREAD

**Issue by roma50** [QuickBlox/q-municate-android#250]
I modified q-municate application android. Before the android sdk was 3.3.5. Now, i upgrade to 3.3.5 to 3.4.1.
after, doing the upgrade of sdk; i am getting this error. Please help me how to solve this issue.

Error:Execution failed for task ':Q-municate_app:processDevDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.1) from [com.android.support:design:26.0.1] AndroidManifest.xml:28:13-35
  	is also present at [com.android.support:support-v4:26.1.0] AndroidManifest.xml:28:13-35 value=(26.1.0).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:26:9-28:38 to override.

**Comment by roma50** [comment]
Full Error Details:

Information:Gradle tasks [:q-municate_auth_service:generateDebugSources, :q-municate_auth_service:generateDebugAndroidTestSources, :q-municate_auth_service:mockableAndroidJar, :q-municate_auth_service:prepareDebugUnitTestDependencies, :Q-municate_db:generateDebugSources, :Q-municate_db:generateDebugAndroidTestSources, :Q-municate_db:mockableAndroidJar, :Q-municate_db:prepareDebugUnitTestDependencies, :Q-municate_core:generateDebugSources, :Q-municate_core:generateDebugAndroidTestSources, :Q-municate_core:mockableAndroidJar, :Q-municate_core:prepareDebugUnitTestDependencies, :Q-municate_app:generateDevDebugSources, :Q-municate_app:generateDevDebugAndroidTestSources, :Q-municate_app:prepareDevDebugUnitTestDependencies, :Q-municate_app:mockableAndroidJar, :q-municate_base_cache:generateDebugSources, :q-municate_base_cache:generateDebugAndroidTestSources, :q-municate_base_cache:mockableAndroidJar, :q-municate_base_cache:prepareDebugUnitTestDependencies, :q-municate_user_cache:generateDebugSources, :q-municate_user_cache:generateDebugAndroidTestSources, :q-municate_user_cache:mockableAndroidJar, :q-municate_user_cache:prepareDebugUnitTestDependencies, :q-municate_base_service:generateDebugSources, :q-municate_base_service:generateDebugAndroidTestSources, :q-municate_base_service:mockableAndroidJar, :q-municate_base_service:prepareDebugUnitTestDependencies, :q-municate_user_service:generateDebugSources, :q-municate_user_service:generateDebugAndroidTestSources, :q-municate_user_service:mockableAndroidJar, :q-municate_user_service:prepareDebugUnitTestDependencies]

Error:Execution failed for task ':Q-municate_app:processDevDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.1) from [com.android.support:design:26.0.1] AndroidManifest.xml:28:13-35
  	is also present at [com.android.support:support-v4:26.1.0] AndroidManifest.xml:28:13-35 value=(26.1.0).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:26:9-28:38 to override.

**Comment by tatanka987** [comment]
https://stackoverflow.com/a/47138345/4850609

**Comment by roma50** [comment]
I have done but stil not going to update successfully sdk from 3.3.35 to 3.4.1

**Comment by tatanka987** [comment]
It means you check not all dependencies. You can see our [**test** branch](https://github.com/QuickBlox/q-municate-android/tree/jenkins_builder) with updated QB SDK to latest version (3.5.1).

**Comment by roma50** [comment]
I am getting this error when i follow the commit of update sdk above link. How to solve this issue please let me know fast. 
Error:(20, 0) Could not get unknown property 'qbRepository' for object of type org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository.

**Comment by tatanka987** [comment]
hi @roma50, just use master branch, about week ago we released new Q-municate version with latest SDK (3.5.2).

**Comment by roma50** [comment]
Please could you give me the exact link and file where i can change sdk. 
Before the android sdk was 3.3.5. Now, i upgrade to 3.3.5 to 3.5.1. During syncing of sdk; i am getting this error. Please help me how to solve this issue.

**Comment by tatanka987** [comment]
[There](https://github.com/QuickBlox/q-municate-android) is master branch with latest QuickBlox Android SDK. To resolve your problem change the parameter [ext.isPrivateRepository](https://github.com/QuickBlox/q-municate-android/blob/master/build.gradle#L13) to '**false**' in your project (in release branch it is 'false' but in branch, which I provided before, it was 'true' because there we used internal repository for internal tests).

**Comment by roma50** [comment]
Its already false. but still issue remains.

  dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath 'io.fabric.tools:gradle:1.+'
        classpath 'com.google.gms:google-services:3.1.1'
    }
}

ext.isPrivateRepository = false

allprojects {
    repositories {
        jcenter()
        maven {
            if (isPrivateRepository) {
                url = qbRepository
                credentials {
                    username qbUser
                    password qbPassword

**Comment by roma50** [comment]
Its already false. but still issue remains.

  dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath 'io.fabric.tools:gradle:1.+'
        classpath 'com.google.gms:google-services:3.1.1'
    }
}

ext.isPrivateRepository = false

allprojects {
    repositories {
        jcenter()
        maven {
            if (isPrivateRepository) {
                url = qbRepository
                credentials {
                    username qbUser
                    password qbPassword

**Comment by tatanka987** [comment]
Do you reproduce first issue or issue about unknown property 'qbRepository'? If second, replace [next code](https://github.com/QuickBlox/q-municate-android/blob/master/build.gradle#L18-L28) to 
`maven { url "https://github.com/QuickBlox/quickblox-android-sdk-releases/raw/master/" } ` 

But I don't understand why do you get any errors, because we tester master branch before release.
